// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // The default docs sidebar can be generated from the docs folder structure
  docSidebar: [{ type: "autogenerated", dirName: "." }],

  components: [
    {
      type: "autogenerated",
      dirName: "components", // Le chemin du dossier contenant vos documents pour components
    },
  ],

  tutorials: [
    {
      type: "autogenerated",
      dirName: "tutorials", // Le chemin du dossier contenant vos documents pour extensions
    },
  ],

  extensions: [
    {
      type: "autogenerated",
      dirName: "extensions", // Le chemin du dossier contenant vos documents pour extensions
    },
  ],
};

module.exports = sidebars;
